# This is a basic workflow to help you get started with Actions

name: Release-HyperKyc

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the "master" branch
  push:
    branches: [ "main" ]
  # pull_request:
    # branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "deploy"
  deploy:
    # The type of runner that the job will run on
    runs-on: macOS-14
    
    # Environment to be used for pushing HyperKYC to cocoapods
    environment: production

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Use latest stable version of xcode
      - uses: maxim-lobanov/setup-xcode@v1
        with:
          xcode-version: '15.2'

      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout repository
        id: checkout_branch
        uses: actions/checkout@v3

      # Runs a set of commands to create tag (x.y.z) and push it to origin
      - name: Create a tag for version x.y.z
        env:
          HYPERKYC_VERSION: ${{ secrets.HYPERKYC_VERSION }}
        run: |
          git tag "$HYPERKYC_VERSION"
          git push origin --tags
    
      # Build HyperKyc SDK (Modify if using workspace/scheme)
      - name: Build iOS SDK
        run: |
          xcodebuild clean build \
          -workspace HyperKYC.xcworkspace \  # Update if needed
          -scheme HyperKYC \  # Update with correct scheme
          -configuration Release \
          -derivedDataPath build

      #  Install Sentry CLI
      - name: Install Sentry CLI
        run: curl -sL https://sentry.io/get-cli/ | bash

      #  Upload dSYM to Sentry
      - name: Upload dSYM to Sentry
        env:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
          SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
        run: |
          export SENTRY_DSYM_PATH="$(find build -name '*.dSYM' -print0 | xargs -0)"
          if [ -z "$SENTRY_DSYM_PATH" ]; then
            echo "No dSYM files found. Skipping upload."
          else
            sentry-cli upload-dsym --org "$SENTRY_ORG" --project "$SENTRY_PROJECT" --auth-token "$SENTRY_AUTH_TOKEN" "$SENTRY_DSYM_PATH"
            echo "dSYM successfully uploaded to Sentry!"
          fi

          
      # Runs a set of commands to push HyperKyc (HYPERKYC_VERSION) to cocoapods
      - name: Push HyperKYC (HYPERKYC_VERSION) to cocoapods
        env:
          COCOAPODS_TRUNK_TOKEN: ${{ secrets.COCOAPODS_TRUNK_TOKEN }}
        run: |
          pod spec lint HyperKYC.podspec --allow-warnings --verbose
          pod trunk push HyperKYC.podspec --allow-warnings
      
      # Runs a command to let you know that HyperKyc (HYPERKYC_VERSION) has been released
      - name: Log HyperKyc (HYPERKYC_VERSION) release
        env: 
          HYPERKYC_VERSION: ${{ secrets.HYPERKYC_VERSION }}
        run: |
          echo HyperKyc "$HYPERKYC_VERSION" has been pushed to cocoapods
